function[anglee]=find_angle(X,Y)
x1=X(1);x2=X(2);x3=X(3);
y1=Y(1);y2=Y(2);y3=Y(3);
if(sum(sign(Y-y1))==0)
   Ymid=y1;Xmid=x1;
   Ylo=Y(find(sign(Y-y1)==1));Xlo=X(find(sign(Y-y1)==1));
   Yup=Y(find(sign(Y-y1)==-1));Xup=X(find(sign(Y-y1)==-1));
end
if(sum(sign(Y-y2))==0)
    Ymid=y2;Xmid=x2;
   Ylo=Y(find(sign(Y-y2)==1));Xlo=X(find(sign(Y-y2)==1));
   Yup=Y(find(sign(Y-y2)==-1));Xup=X(find(sign(Y-y2)==-1));
end
if(sum(sign(Y-y3))==0)
   Ymid=y3;Xmid=x3;
   Ylo=Y(find(sign(Y-y3)==1));Xlo=X(find(sign(Y-y3)==1));
   Yup=Y(find(sign(Y-y3)==-1));Xup=X(find(sign(Y-y3)==-1));
end

m1=(Ylo-Ymid)/(Xmid-Xlo);
m2=(Yup-Ymid)/(Xmid-Xlo);
anglee=(m1-m2)/(1+m1*m2);
anglee=180-abs(atan(anglee)*180/pi);