function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Jan-2013 20:03:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-3.5 3.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-3.5 3.5]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 0 1],'MarkerSize',15,'Marker','.',...
    'LineStyle','none');

