function createfigure1(X1, Y1, X2, YMatrix1,YMatrix2)
%CREATEFIGURE1(X1,Y1,X2,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jan-2013 20:26:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2.5 2.5]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 0 1],'MarkerSize',20,'Marker','.',...
    'LineStyle','none');

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1);
set(plot1(1),'Color',[1 0 1]);
% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix2);
set(plot1(1),'Color',[0 1 0]);

