clear all;
disp('                                       HIGH PASS FILTER');
Wp=input('Enter passband frequency=');
Ws=input('Enter stopband frequency=');
Rp=input('Enter passband ripple=');
Rs=input('Enter stopband ripple=');
Fs=input('Enter sampling frequency=');
Wp=(2*Wp/Fs);
Ws=(2*Ws/Fs);
[N,Wn]=buttord(Wp,Ws,Rp,Rs);
[B,A]=butter(N,Wn,'high');
freqz(B,A,512,Fs);
[H,w] = freqz(B,A);
a=20*log10(abs(H));
figure;%subplot(6,1,1);
plot(w/pi*Fs/2,a);
title('IIR HPF');
ylabel('MAGNITUDE in dB');
xlabel('Frequency Hertz');
grid on;
b=angle(H);
figure;%subplot(6,1,2);
c=unwrap(b);
plot(w/pi*Fs/2,b*180/pi);
ylabel('PHASE in Degrees');
xlabel('Frequency Hertz');
grid on
Fss=20000;
t=0:1/Fss:1;
o=sin(2*pi*500*t);
d=sin(2*pi*1500*t);
e=sin(2*pi*2500*t);
f=sin(2*pi*3500*t);
g=sin(2*pi*4500*t);
ff=t*Fss-Fss/2;
h=d+e+g+f+o;
figure;%subplot(6,1,3);
plot(t(1:500),h(1:500));
ylabel('INPUT');
i=abs(fftshift(fft(h)))/(Fss/2);
figure;%subplot(6,1,4);
plot(ff((Fss/2):(Fss/2+Fs/2)),i((Fss/2):(Fss/2+Fs/2)));
ylabel('INPUT FFT');

m=filter(B,A,h);
figure;%subplot(6,1,5);
plot(t(1:500),m(1:500));
ylabel('FILTER OUT');
k=abs(fftshift(fft(m)))/(Fss/2);
figure;%subplot(6,1,6);
plot(ff((Fss/2):(Fss/2+Fs/2)),k((Fss/2):(Fss/2+Fs/2)));
ylabel('OUTPUT FFT');
disp(N);