function [figure1]=createfigure2(X1, Y1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16,h)
%CREATEFIGURE2(X1,Y1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  X4:  vector of x data
%  X5:  vector of x data
%  X6:  vector of x data
%  X7:  vector of x data
%  X8:  vector of x data
%  X9:  vector of x data
%  X10:  vector of x data
%  X11:  vector of x data
%  X12:  vector of x data
%  X13:  vector of x data
%  X14:  vector of x data
%  X15:  vector of x data
%  X16:  vector of x data

%  Auto-generated by MATLAB on 03-Feb-2013 22:57:17

% Create figure
figure1 = h;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 255]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Color',[0 0.498039215803146 0]);

% Create plot
plot(X2,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X3,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X4,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X5,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X6,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X7,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X8,X1,'LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X9,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X10,X1,'LineWidth',2);

% Create plot
plot(X11,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X12,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X13,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X14,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X15,X1,'LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X16,X1,'LineWidth',2,'Color',[1 0 0]);

